### ISSUE TITLE
Disable prompt asking for more files: Preloaded files has reached upper limit

### ISSUE THREAD

**Issue by poetaman** [josa42/coc-lua#59]
What option can I use to disable prompt asking for more files?

<img width="1204" alt="Screen Shot 2021-03-30 at 4 56 14 AM" src="https://user-images.githubusercontent.com/71736629/112985031-80ba5280-9114-11eb-95d8-4dd6d68408d1.png">

**Comment by poetaman** [comment]
@josa42 This prompt shows for all files I open, but maybe dependent on the current working directory. Not sure though, anyway given its asynchronous, it is distracting to have this open for every file. Ideally there would be a variable/option that controls disabling this prompt.

**Comment by oblitum** [comment]
Disabling option should be useful to have, but I guess this was triggered by #58 in the first place, which is already fixed upstream.

**Comment by poetaman** [comment]
@oblitum Not sure what you mean, I still get this problem. And coc's author says this: https://github.com/sumneko/lua-language-server/issues/480#issuecomment-843839861

**Comment by oblitum** [comment]
@reportaman I speculate you're getting this prompt in the first place because you're getting your home folder being scanned, like on #58, but this has been fixed upstream: https://github.com/neoclide/coc.nvim/issues/3102#issuecomment-848308790.

**Comment by oblitum** [comment]
It's still an useful option to have though, in real usecases where actual workspace folder (not home folder) has too many files (though I was never able to hit this).

**Comment by poetaman** [comment]
@oblitum Hmm, do I need to do something special to try the new behavior?

**Comment by oblitum** [comment]
@reportaman just update coc.nvim to latest. I used to have this issue too regarding home folder scan, but since [`39c14a3`](https://github.com/neoclide/coc.nvim/issues/3102#issuecomment-848308790) I don't face it anymore when opening files from home.
